### ISSUE TITLE
Can't initialize a GeBlocks client in the main agent

### ISSUE THREAD

**Issue by NizarNadif** [nicolomarconi02/robotics-project#1]
I can't initialize a [`GetBlocks`](https://github.com/nicolomarconi02/robotics-project/commit/733e53134426d75183234541730a65bdac3c48c9) service's client from the C++ main agent, I get a namespace error during the compilation time.
https://github.com/nicolomarconi02/robotics-project/blob/e101ace558dea3d36c3455ee4d026aa912416393/src/main.cpp#L22

**Comment by GioLor33** [comment]
The project works correctly on a Windows 11 system using WSL Ubuntu 20.04 and Docker with ROS installed. The setup is functioning as expected.
